### ISSUE TITLE
always getting a 400 response on access token post request

### ISSUE THREAD

**Issue by christiaan20** [Mc-Auth-com/Mc-Auth#145]
I'm trying to integrate your Oauth procedure in my python-flask website using the flask auth client of [OauthLib](https://docs.authlib.org/en/stable/client/flask.html) on python3.8. I have made an account under the minecraft user chryonicWolf and I the first part doing a GET https://mc-auth.com/oAuth2/authorize with my client ID goes fine. But trying to do the POST https://mc-auth.com/oAuth2/token always returns : 
`
{
    "error": 400,
    "message": "client_id does not exist or does not match client_secret"
}
`

Things I've tried to do:
1. Going deeper into the OauthLib to see if they construct the POST request with missing headers and trying to add everything that is described in your documentation.
2. refreshing the client_secret 
3. Trying to do the entire Oauth2.0 procedure with Postman also gives the same error
4. Doing the login part with my website and simulating the 2nd part with Postman where I control each aspect of the POST request very closely also doesnt work.

All of this doesn't work and I'm starting to feel it is a problem at your server. Because the first part works so the redirect url and client_id should be ok. I refreshed and checked the client_secret so it also should be correct.

**Comment by SpraxDev** [comment]
Thanks for using Mc-Auth and reporting a potential bug!
I am currently very busy but I'll be able to take a look in about a week.

**Comment by christiaan20** [comment]
> Thanks for using Mc-Auth and reporting a potential bug!
> I am currently very busy but I'll be able to take a look in about a week.

Thx for the heads up, I can definitely wait a week

**Comment by SpraxDev** [comment]
Can you share some kind of debug log showing headers and body? (**please anonymize at least *client_secret***).

I've created a new test application and everything seems to work fine for me.

I've exported my test collection, maybe you can spot a difference: [Mc-Auth.postman_collection.zip](https://github.com/Mc-Auth-com/Mc-Auth/files/6453864/Mc-Auth.postman_collection.zip)

**Comment by SpraxDev** [comment]
Not sure if you caused some 500 errors or somebody else, but I've fixed the error handling for invalid JSON body/data - Maybe that helps with your issue.

**Comment by christiaan20** [comment]
Thx for the postman collection that was really usefull to clearly see how the post request needs to build. You should consider making the information available in your github wiki since it is more complete. 

Anyway I got it to work by building the second Post request manually in python but I suggest you make your Oauth procedure compatible with standardised OauthV2 procedures such as those used in the OauthLib and the postman Oauth feature. That would make increase the usability of your API making it more attractive to work with for developers.

But If that is not something you have planned for the future. I'll post the code that I got working here if somebody else wants to implement this in their python flask server.

```
# Oauth to McAuth
oauth = OAuth(app)
oauth.register(name="mcauth",access_token_url="https://mc-auth.com/oAuth2/token",authorize_url="https://mc-auth.com/oAuth2/authorize",client_id=os.getenv("CLIENT_ID"),client_secret=os.getenv("CLIENT_SECRET"))

@app.route("/auth_mc_auth", methods=["GET"])
def authenticateUserMcAuth():
    base_url = request.url.split("/auth_mc_auth")[0]
    redirect_uri = base_url + '/completed_mc_auth'
    return oauth.mcauth.authorize_redirect(redirect_uri,scope="profile")



@app.route('/completed_mc_auth', methods=['GET','POST'])
def completeUserMcAuth():
    params = oauth.mcauth.retrieve_access_token_params(request, None)

    # so the post request parameters already contain the code, state and redirect_url parameters
    # add client_id, client secret and grant_type to the parameters of the post request
    params['client_id'] = oauth.mcauth.client_id
    params['client_secret'] = oauth.mcauth.client_secret
    params['grant_type'] = 'authorization_code'


    # add basic headers for content type
    headers = {'Content-Type': 'application/json',
               'Accept': 'application/json'}

    r = requests.post(oauth.mcauth.access_token_url, json=params,headers=headers)


    if r.ok:
        # if response has code 200, so it is a proper response extract the name and id from the player
        jsonData = r.json()
        profile = jsonData.get('data').get('profile')
        id = profile.get('id')
        name = profile.get('name')


        return render_template('auth_mc_auth.html',user=current_user,username=name,id=id)
    else:
        message= r.text + " </br>Try again with McAuth or log in with a mojang account. </br>If the problem persists contact me via the contact page."
        flash(message)
        return redirect(url_for('prelogin'))


```

**Comment by SpraxDev** [comment]
Thanks for your feedback and sharing the code!

Mc-Auth should be fully OAuth2.0 compliant but I'll take a deeper look (You can follow #152 if you are interested in that).

The same goes for the documentation. I've create a new issue (#151) to not forget about that.

Please don't hesitate to ask further questions if there are any ^^
