### ISSUE TITLE
Autofill username box.

### ISSUE THREAD

**Issue by chezzzer** [Mc-Auth-com/Mc-Auth#276]
**Is your feature request related to a problem? Please describe.**
My users are getting frustrated having to enter their username

**Describe the solution you'd like**
It would be very helpful if a query parameter was added (like &username=) to autofill the username input box on the /oAuth2/authorize page.

**Comment by SpraxDev** [comment]
I've added a `mcauth.username` parameter that you can now provide to Mc-Auth on the authorize route.

If a user is not logged in yet and redirected to the login page, the provided value is used for the username input.

Would be great if you could report back if everything works as expected ^^

**Comment by chezzzer** [comment]
Works flawlessly, tysm for the quick response and implementation. Legend!
